{% set CONDA_PY = os.environ['CONDA_PY']  %}
{% set PY = CONDA_PY | int  %}
name: esss-fix-format-py{{ PY }}

dependencies:
  # run
  - boltons
  - clangdev>=6.0.1
  - click>=6.0
  - isort>=5.0
  - python=3.{{ CONDA_PY[1:] }}
  - tomli

  - attrs <=20  # [PY==36]
  - platformdirs <=2.4  # [PY==36]
  - typing-extensions <4  # [PY==36]
  - typing-extensions <5.11  # [PY==36]

  # develop
  - black
  - pre-commit
  - pygments>=2.2.0
  - pytest>=3.8.0
  - pytest-mock>=1.10.0

environment:
  PYTHONPATH:
    - {{ root }}/src
  PATH:
    - {{ root }}/bin
