{% set CONDA_PY = os.environ.get('CONDA_PY', '36') %}
name: esss-fix-format-py{{ CONDA_PY }}

dependencies:
  # run
  - boltons
  - clangdev>=6.0.1
  - click>=6.0
  - isort>=5.0
  - python={{ '.'.join(CONDA_PY) }}
  - pydevf==0.1.5
  - toml>=0.8.0

  # develop
  - black
  - pre-commit
  - pygments>=2.2.0
  - pytest>=3.8.0
  - pytest-mock>=1.10.0

environment:
  PYTHONPATH:
    - {{ root }}/src
  PATH:
    - {{ root }}/bin
