[tool.black]
line-length = 100

[tool.mypy]
files = "src,tests"
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
local_partial_types = true
ignore_missing_imports_per_module = true
disallow_untyped_defs = true
