name: test

on:
  push:
    branches:
      - master

  pull_request:

# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        conda_py: ["36", "310"]
        os: ["windows-latest", "ubuntu-latest"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: ''
        channels: conda-forge,esss
        channel-priority: true
    - name: Install
      env:
        CONDA_PY: ${{ matrix.conda_py }}
      run: |
        conda config --system --set always_yes yes --set changeps1 no
        conda install -c conda-forge conda-devenv
        conda info -a
        conda devenv
    - name: Tests
      run: |
        conda run --live-stream -n esss-fix-format-py${{ matrix.conda_py }} pytest
