name: windows

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - CONDA_PY: "36"
          - CONDA_PY: "37"

    steps:
    - uses: actions/checkout@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ''
    - name: Install
      shell: powershell
      run: |
        conda config --system --set always_yes yes --set changeps1 no
        conda config --system --append channels conda-forge
        conda config --system --append channels esss
        conda install -c conda-forge conda-devenv
        conda info -a
        conda devenv
    - name: Tests
      shell: powershell
      run: |
        conda activate esss-fix-format-py${{ matrix.CONDA_PY }}
        flake8 src tests
        rst-lint CHANGELOG.rst README.rst
        pytest
        fix-format -k .
